name: writeright
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  # For backend models
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  logger: ^2.5.0
  device_info_plus: ^9.1.0 # check android api level
  permission_handler: ^12.0.0+1
  just_audio: ^0.10.4
  auto_size_text: ^3.0.0
  image_picker: ^0.8.7
  flutter_secure_storage: ^9.2.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  go_router: ^15.2.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # For backend models
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/avatar.png
    - assets/images/dolphin.png
    - assets/images/incorrect_word.png
    - assets/images/ocean-bg.png
    - assets/images/diver.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
